# Generated by Django 3.2.3 on 2021-06-14 23:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturing_tracker',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('order_placed_date', models.DateField()),
                ('client_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=20)),
                ('is_vote', models.BooleanField(blank=True, default=False, null=True)),
                ('is_home', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(default='', upload_to='image/')),
                ('color', models.CharField(default='', max_length=15)),
                ('style_code', models.CharField(default='', max_length=15)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('dislike_count', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(choices=[('tshirts', 'tshirts'), ('shirts', 'shirts'), ('jeans', 'jeans')], default='', max_length=256)),
                ('size_available', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='', max_length=256)),
                ('pdetails', models.CharField(default='', max_length=500)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='style_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_code', models.CharField(default='', max_length=100)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('fabric inhouse', 'fabric inhouse'), ('cutting', 'cutting'), ('printing and labelling', 'printing and labelling'), ('stitching', 'stitching'), ('ironing packing', 'ironing packing'), ('quality check', 'quality check'), ('shipped', 'shipped')], default='', max_length=256)),
                ('image', models.ImageField(default='', upload_to='image/')),
                ('expected_delivery_date', models.DateField(default=datetime.datetime.now)),
                ('prd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturing_tracker')),
            ],
        ),
    ]
